# Generated by Django 3.0.7 on 2020-12-27 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20201227_1323'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Info',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='recipe',
            new_name='info',
        ),
    ]
