# Generated by Django 3.0.7 on 2021-01-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20210101_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='count',
        ),
        migrations.AddField(
            model_name='info',
            name='servings',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='info',
            name='time',
            field=models.CharField(default='30 min', max_length=200),
        ),
        migrations.AlterField(
            model_name='info',
            name='intro',
            field=models.CharField(default='Needs no intro', max_length=4000),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='measurment',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('order', models.IntegerField(default=0)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Info')),
            ],
        ),
    ]
