# Generated by Django 3.0.7 on 2021-01-04 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20210104_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttoshop',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.Ingredient'),
        ),
    ]
