# Generated by Django 5.2.15 on 2026-06-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_ingredienttype_is_staple'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Friendly name, e.g. 'AllRecipes'", max_length=100)),
                ('base_url', models.URLField(help_text='e.g. https://www.allrecipes.com')),
                ('search_url_pattern', models.CharField(blank=True, help_text='Search URL with {query} placeholder, e.g. https://www.allrecipes.com/search?q={query}', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='info',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='info',
            name='last_cooked',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Notes to improve it next time'),
        ),
        migrations.AddField(
            model_name='info',
            name='score',
            field=models.IntegerField(blank=True, help_text='Your score 1–10', null=True),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dinnercomponent',
            name='default_selected',
            field=models.BooleanField(default=True, help_text='Pre-check this component on the dinner page'),
        ),
        migrations.AlterField(
            model_name='dinnercomponent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dinnercomponent',
            name='order',
            field=models.IntegerField(default=0, help_text='Lower number = shown first'),
        ),
        migrations.AlterField(
            model_name='dinnercomponent',
            name='role',
            field=models.CharField(default='Main', help_text='Free text label, e.g. Main, Side, Sauce, Bread', max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredienttoshop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='instruction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recipetag',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tagg',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
