# Generated by Django 5.2.15 on 2026-06-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_ingredienttoshop_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttype',
            name='is_always_available',
            field=models.BooleanField(default=False, help_text='Always available without buying (water, etc.) — never shown on shopping list or in pantry'),
        ),
        migrations.AlterField(
            model_name='ingredienttype',
            name='is_staple',
            field=models.BooleanField(default=False, help_text='Pantry staple (salt, oil, spices, etc.) — track in pantry and buy if needed, but no urgency to use up'),
        ),
    ]
